-- Generated by scripts/generate-supabase-seed-sql.mjs
BEGIN;

INSERT INTO "public"."SourceDocument" ("id","code","title","filePath","revisionDate","checksum","createdAt","updatedAt")
VALUES ('src_ket_2024_12_01','KET-2024-12-01','Keliu eismo taisykles (atnaujinta 2024-12-01)','Data/KET-knygute-2024-2025-(1).pdf','2024-12-01'::timestamp,NULL,NOW(),NOW())
ON CONFLICT ("code") DO UPDATE SET "title" = EXCLUDED."title", "filePath" = EXCLUDED."filePath", "revisionDate" = EXCLUDED."revisionDate", "checksum" = EXCLUDED."checksum", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_16','src_ket_2024_12_01','16','Tikrinancio pareiguno sustabdytas vairuotojas privalo sustoti ir dokumentus paduoti neislipes is transporto priemones.','11-12','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_20','src_ket_2024_12_01','20','Judant transporto priemonei draudziama naudotis telefonu rankoje; leidziama laisvu ranku iranga, kai telefonas laikiklyje, arba naudojant transporto priemones iranga.','12','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_27','src_ket_2024_12_01','27','Sukdamas sankryzoje arba ivaziuodamas/isvaziuodamas is teritorijos vairuotojas privalo praleisti pestiji, kurio judejimo krypti kerta.','14','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_30','src_ket_2024_12_01','30','Artejant prie nereguliuojamos pesciuju perejos vairuotojas privalo suletinti arba sustoti ir praleisti pesciuosius pagal ju uzimama juosta.','14','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_31','src_ket_2024_12_01','31','Jei pries pereja sustojo ar suletejo transporto priemone, ta pacia kryptimi vaziuojantis vairuotojas privalo sustoti ar suletinti ir isitikinti, kad perejoje saugu.','14-15','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_32','src_ket_2024_12_01','32','Draudziama ivaziuoti i pesciuju pereja, jei pesciai, kuriuos privaloma praleisti, neisejo is uzimamos juostos, arba uz perejos kliutis vercia sustoti.','15','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_91_3','src_ket_2024_12_01','91.3','Avarine sviesos signalizacija privalo buti ijungta, kai transporto priemone sustabde tikrinantis pareigunas.','32','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_104','src_ket_2024_12_01','104','Persirikiuodamas vairuotojas privalo duoti kelia gretima juosta ta pacia kryptimi vaziuojancioms transporto priemonems.','35','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_105','src_ket_2024_12_01','105','Jei viena juosta uzblokuota ir susidare eile, gretima juosta vaziuojantis vairuotojas privalo ileisti viena pirma eileje esancia transporto priemone.','35','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_112','src_ket_2024_12_01','112','I keli is greitejimo juostos isiliejantis vairuotojas privalo duoti kelia pagrindiniu srautu vaziuojancioms transporto priemonems.','36','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_119','src_ket_2024_12_01','119','Vairuotojas privalo vaziuoti kuo arciau desiniojo vaziuojamosios dalies krasto.','38','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_125','src_ket_2024_12_01','125','Draudziama ta pacia kryptimi vaziuojancias transporto priemones apvaziuoti is desines vaziuojant kelkrasciu, letejimo ar greitejimo juosta (su isimtimis sukantiems i kaire).','39','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_129','src_ket_2024_12_01','129','Gyvenvietese visoms transporto priemonems leidziama vaziuoti ne didesniu kaip 50 km/h greiciu.','41','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_130','src_ket_2024_12_01','130','Stovejimo aikstelese visoms transporto priemonems leidziama vaziuoti ne didesniu kaip 20 km/h greiciu.','41','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_131_1','src_ket_2024_12_01','131.1','Lengviesiems automobiliams, motociklams ir triraciams ne gyvenvietese taikomi sezoniniai maksimalus greiciai: automagistraleje 130/110, greitkelyje 120/110, kitur 90 arba 70.','41','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_131_2','src_ket_2024_12_01','131.2','Pradedantiesiems vairuotojams automagistraleje leidziama iki 100 km/h, greitkelyje iki 90 km/h, asfalto ar betono keliuose iki 80 km/h, kituose keliuose iki 70 km/h.','41','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_132','src_ket_2024_12_01','132','Kelio zenklu nustatytas greitis negali virsyti 131 punkte konkreciai transporto priemonei nustatyto maksimalaus leistino greicio.','42','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_154','src_ket_2024_12_01','154','Nelygiareiksmiu keliu sankryzoje salutiniu keliu vaziuojantis vairuotojas privalo duoti kelia pagrindiniu keliu artejancioms transporto priemonems.','49','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_155','src_ket_2024_12_01','155','Lygiareiksmiu keliu sankryzoje duodamas kelias is desines artejancioms transporto priemonems, jei trajektorijos kertasi.','49','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_157','src_ket_2024_12_01','157','Sukdamas i kaire vairuotojas privalo duoti kelia priesinga kryptimi tiesiai ar i desine vaziuojancioms transporto priemonems ir leistinai lenkiancioms transporto priemonems.','49','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_158','src_ket_2024_12_01','158','Sukdamas sankryzoje i kaire arba i desine vairuotojas privalo duoti kelia eismo dalyviams, kertantiems juostas i kurias jis suka, iskaitant dviracius.','49','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_160','src_ket_2024_12_01','160','Draudziama ivaziuoti i sankirta, jei joje ar uz jos kliutis priverstu sustoti sankryzoje ir trukdyti kitu transporto priemoniu eismui.','49','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_163','src_ket_2024_12_01','163','Vaziuodamas pagal papildomos sviesoforo sekcijos rodykle su raudonu arba geltonu signalu vairuotojas privalo duoti kelia is kitu krypciu leidziamu signalu judantiems eismo dalyviams.','50','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_169','src_ket_2024_12_01','169','Gelezinkelio pervazoje eismo dalyvis privalo duoti kelia artejanciai beginei transporto priemonei.','51','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_170','src_ket_2024_12_01','170','Kai vaziuoti per gelezinkelio pervaza draudziama arba duodamas kelias traukiniui, vairuotojas privalo sustoti pries stop linija/zenkla/uztvara ar ne arciau kaip 10 m nuo pirmojo begio.','51','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_173_4','src_ket_2024_12_01','173.4','Draudziama ivaziuoti i gelezinkelio pervaza, jeigu uz jos yra kliutis, kuri verstu sustoti ant pervazos.','52','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_219_1','src_ket_2024_12_01','219.1','Ivykus eismo ivykiui privaloma nedelsiant sustoti ir pazymeti ivykio vieta pagal taisykles.','68','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_219_3','src_ket_2024_12_01','219.3','Eismo ivykyje dalyvaujantis asmuo privalo pateikti asmens tapatybes ar vairuotojo pazymejima ir draudimo duomenis, jei to reikalauja kiti susije dalyviai.','68','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_220','src_ket_2024_12_01','220','Jei eismo ivykyje nera zuvusiu ar suzeistu ir dalyviai sutaria del aplinkybiu, pildoma deklaracija ir policija nekvieciama; nesutarus kvieciama policija.','68','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_kelio_zenklas_201','src_ket_2024_12_01','KELIO_ZENKLAS_201','Kelio zenklas 201 nurodo pagrindini kelia ir suteikia pirmenybe vaziuoti per nereguliuojamas sankryzas.','82','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."RuleClause" ("id","sourceDocumentId","sectionCode","excerptLt","pageRef","evidenceLevel","createdAt","updatedAt")
VALUES ('cl_ket_2024_12_01_kelio_zenklas_203','src_ket_2024_12_01','KELIO_ZENKLAS_203','Kelio zenklas 203 Duoti kelia ipareigoja duoti kelia kertamuoju ar prisijungianciuoju keliu vaziuojancioms transporto priemonems.','82','PRIMARY',NOW(),NOW())
ON CONFLICT ("sourceDocumentId","sectionCode") DO UPDATE SET "excerptLt" = EXCLUDED."excerptLt", "pageRef" = EXCLUDED."pageRef", "evidenceLevel" = EXCLUDED."evidenceLevel", "updatedAt" = NOW();

INSERT INTO "public"."ExamProfile" ("id","code","label","timeLimitSec","questionCount","passThresholdPct","evidenceStatus","note","createdAt","updatedAt")
VALUES ('exam_regitra_sim_v1','REGITRA_SIM_V1','Regitra simuliacija',1800,15,NULL,'INSUFFICIENT_RULE_BASIS','Oficialus teorijos vertinimo slenkstis nepateiktas pateiktoje medzagoje.',NOW(),NOW())
ON CONFLICT ("code") DO UPDATE SET "label" = EXCLUDED."label", "timeLimitSec" = EXCLUDED."timeLimitSec", "questionCount" = EXCLUDED."questionCount", "passThresholdPct" = EXCLUDED."passThresholdPct", "evidenceStatus" = EXCLUDED."evidenceStatus", "note" = EXCLUDED."note", "updatedAt" = NOW();

COMMIT;
