-- Generated by scripts/generate-supabase-seed-sql.mjs
BEGIN;

-- SC-001
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_001','SC-001','sc-001-mobile-usage','multi','Mobile usage','EASY','Vairuotojas vaziuodamas miesto gatve gauna skambuti.','Kada leidziama naudotis mobiliuoju rysiu vairuojant?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_001_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage'),'A','Kai telefonas laikomas rankoje ir eismas neintensyvus',FALSE,NULL,'Neteisinga, nes naudojimasis telefonu rankomis judant transporto priemonei draudziamas (Nuoroda: KET 20).',NOW(),NOW()),
  ('qo_sc_001_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage'),'B','Kai naudojama laisvu ranku iranga, o telefonas pritvirtintas laikiklyje',TRUE,NULL,'Teisinga, nes KET leidzia valdyti rysio priemone su laisvu ranku iranga, kai telefonas laikiklyje (Nuoroda: KET 20).',NOW(),NOW()),
  ('qo_sc_001_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage'),'C','Kai transporto priemone stovi ir nedalyvauja eisme',TRUE,NULL,'Teisinga, nes draudimas taikomas, kai transporto priemone dalyvauja viesajame eisme (Nuoroda: KET 20).',NOW(),NOW()),
  ('qo_sc_001_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage'),'D','Kai vaziuojama ne didesniu kaip 30 km/h greiciu',FALSE,NULL,'Neteisinga, nes KET nenumato greicio isimties naudojimui telefonu rankoje (Nuoroda: KET 20).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_001_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-001-mobile-usage'),'cl_ket_2024_12_01_20',TRUE,NOW());

-- SC-002
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_002','SC-002','sc-002-officer-stop','multi','Officer stop','EASY','Policijos pareigunas sustabdo jus dokumentu patikrai.','Kokie veiksmai yra teisingi sustabdzius pareigunui?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_002_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'A','Sustabdyti transporto priemone pagal pareiguno nurodyma',TRUE,NULL,'Teisinga, nes tikrinancio pareiguno stabdomas vairuotojas privalo sustoti (Nuoroda: KET 16).',NOW(),NOW()),
  ('qo_sc_002_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'B','Ijungti avarine sviesos signalizacija',TRUE,NULL,'Teisinga, nes sustabdzius tikrinanciam pareigunui avarine signalizacija turi buti ijungta (Nuoroda: KET 91.3).',NOW(),NOW()),
  ('qo_sc_002_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'C','Dokumentus paduoti neislipus is transporto priemones',TRUE,NULL,'Teisinga, nes dokumentai pareigunui paduodami neislipant, o islipti galima tik leidus (Nuoroda: KET 16).',NOW(),NOW()),
  ('qo_sc_002_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'D','Nedelsiant islipti ir prieiti prie pareiguno',FALSE,NULL,'Neteisinga, nes vairuotojui islipti leidziama tik tikrinanciam pareigunui leidus (Nuoroda: KET 16).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_002_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'cl_ket_2024_12_01_16',TRUE,NOW()),
  ('qr_sc_002_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-002-officer-stop'),'cl_ket_2024_12_01_91_3',TRUE,NOW());

-- SC-003
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_003','SC-003','sc-003-eismo-ivykis-deklaracija','single','Eismo ivykis','MEDIUM','Avarijoje niekas nesuzeistas, abi puses sutaria del aplinkybiu.','Ka privalo padaryti eismo ivykio dalyviai?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_003_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'A','Uzpildyti eismo ivykio deklaracija, pasirasyti ir tik tada pasitraukti',TRUE,NULL,'Teisinga, nes be nukentejusiu ir sutariant del aplinkybiu pildoma deklaracija su parasais; nesutarus kvieciama policija (Nuoroda: KET 220).',NOW(),NOW()),
  ('qo_sc_003_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'B','Is karto issiskirstyti, nes zala tik turtine',FALSE,NULL,'Neteisinga, nes privaloma uzfiksuoti ivykio aplinkybes deklaracijoje ir atlikti pareigas po ivykio (Nuoroda: KET 219.1, 220).',NOW(),NOW()),
  ('qo_sc_003_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'C','Visais atvejais butina kviesti policija',FALSE,NULL,'Neteisinga, nes jei nera suzeistu ir dalyviai sutaria, policijos kviesti nereikia (Nuoroda: KET 220).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_003_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'cl_ket_2024_12_01_219_1',TRUE,NOW()),
  ('qr_sc_003_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'cl_ket_2024_12_01_219_3',TRUE,NOW()),
  ('qr_sc_003_3',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-003-eismo-ivykis-deklaracija'),'cl_ket_2024_12_01_220',TRUE,NOW());

-- SC-004
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_004','SC-004','sc-004-priority-order','ordering','Right-of-way signs','HARD','Sankryzoje pagrindinis kelias pazymetas zenklu 201. Viena transporto priemone vaziuoja salutiniu keliu su zenklu 203.','Sudeliokite transporto priemones judejimo seka nuo pirmos iki paskutines.','/scenarios/right-of-way-signs.svg','PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_004_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'A','Melynas automobilis pagrindiniu keliu vaziuoja tiesiai',TRUE,1,'Teisinga, nes tiesiai pagrindiniu keliu vaziuojanti transporto priemone vaziuoja pirma (Nuoroda: KET 154, zenklas 201).',NOW(),NOW()),
  ('qo_sc_004_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'B','Zalias automobilis pagrindiniu keliu suka i kaire',TRUE,2,'Teisinga, nes pagrindiniame kelyje sukantis i kaire vairuotojas praleidzia priesinga krypti, taciau vis tiek turi pirmenybe pries salutini kelia (Nuoroda: KET 157, 154).',NOW(),NOW()),
  ('qo_sc_004_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'C','Oranzinis automobilis atvaziuoja salutiniu keliu',TRUE,3,'Teisinga, nes salutiniu keliu vaziuojantis vairuotojas duoda kelia pagrindinio kelio transportui (Nuoroda: KET 154, zenklas 203).',NOW(),NOW()),
  ('qo_sc_004_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'D','Papildomas dalyvis be pirmumo santykio siame scenarijuje',FALSE,NULL,'Neteisinga, nes sioje uzduotyje pirmumo seka nustatoma tik trim pavaizduotoms transporto priemonems (Nuoroda: KET 154, 157).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_004_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'cl_ket_2024_12_01_154',TRUE,NOW()),
  ('qr_sc_004_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'cl_ket_2024_12_01_157',TRUE,NOW()),
  ('qr_sc_004_3',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'cl_ket_2024_12_01_kelio_zenklas_201',TRUE,NOW()),
  ('qr_sc_004_4',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-004-priority-order'),'cl_ket_2024_12_01_kelio_zenklas_203',TRUE,NOW());

-- SC-005
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_005','SC-005','sc-005-equal-intersection','image','Equal intersection','MEDIUM','Prie sankryzos nera pirmuma nustatanciu zenklu.','Kokia taisykle taikoma lygiareiksmeje sankryzoje?','/scenarios/equal-intersection.svg','PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_005_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection'),'A','Duoti kelia is desines artejanciai transporto priemonei',TRUE,NULL,'Teisinga, nes lygiareiksmeje sankryzoje taikoma desines rankos taisykle (Nuoroda: KET 155).',NOW(),NOW()),
  ('qo_sc_005_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection'),'B','Vaziuoti pirmam, nes zenklu nera',FALSE,NULL,'Neteisinga, nes zenklu nebuvimas nereiskia pirmenybes; taikoma desines rankos taisykle (Nuoroda: KET 155).',NOW(),NOW()),
  ('qo_sc_005_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection'),'C','Vaziuoti pirmam parodzius posukio signala',FALSE,NULL,'Neteisinga, nes signalas nesuteikia pirmenybes (Nuoroda: KET 155 ir bendras principas).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_005_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-005-equal-intersection'),'cl_ket_2024_12_01_155',TRUE,NOW());

-- SC-006
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_006','SC-006','sc-006-left-turn-priority','multi','Left turn priority','MEDIUM','Jus sankryzoje sukate i kaire.','Ka privalote praleisti sukdami i kaire?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_006_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority'),'A','Priesinga kryptimi tiesiai vaziuojancias transporto priemones',TRUE,NULL,'Teisinga, nes sukant i kaire jos turi pirmenybe (Nuoroda: KET 157).',NOW(),NOW()),
  ('qo_sc_006_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority'),'B','Priesinga kryptimi i desine sukancias transporto priemones',TRUE,NULL,'Teisinga, nes jos taip pat priskiriamos priesingai krypciai su pirmenybe jusu atzvilgiu (Nuoroda: KET 157).',NOW(),NOW()),
  ('qo_sc_006_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority'),'C','Niekieno, jei posukio signalas ijungtas is anksto',FALSE,NULL,'Neteisinga, nes posukio signalas nesuteikia važiavimo pirmumo (Nuoroda: KET 157).',NOW(),NOW()),
  ('qo_sc_006_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority'),'D','Lenkiancias transporto priemones, kai sankryzoje lenkti leidziama',TRUE,NULL,'Teisinga, nes taisykle tiesiogiai numato praleisti ir leistina lenkima atliekancias transporto priemones (Nuoroda: KET 157).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_006_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-006-left-turn-priority'),'cl_ket_2024_12_01_157',TRUE,NOW());

-- SC-007
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_007','SC-007','sc-007-turning-across-users','multi','Turning across users','HARD','Sukate sankryzoje i desine, o jusu ivaziavimo juostas kerta pestieji ir dviratininkas.','Koks teisingas veiksmas?','/scenarios/turning-across-users.svg','PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_007_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'A','Praleisti juostas kertancius dviratininkus ir kitus eismo dalyvius',TRUE,NULL,'Teisinga, nes sukdamas vairuotojas privalo duoti kelia kertantiems eismo dalyviams (Nuoroda: KET 158).',NOW(),NOW()),
  ('qo_sc_007_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'B','Praleisti pestiji, kurio judejimo krypti kertate',TRUE,NULL,'Teisinga, nes pestysis praleidziamas tiek sankryzoje, tiek ivaziuojant/isvaziuojant is teritoriju (Nuoroda: KET 27, 158).',NOW(),NOW()),
  ('qo_sc_007_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'C','Vaziuoti pirmam, jei ijungtas posukio signalas',FALSE,NULL,'Neteisinga, nes signalas nesuteikia pirmumo teises, o sukant privaloma duoti kelia kertantiems dalyviams (Nuoroda: KET 158).',NOW(),NOW()),
  ('qo_sc_007_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'D','Praleisti tik viena artimiausia juosta kertanti pesciaji',FALSE,NULL,'Neteisinga, nes sukant duodamas kelias eismo dalyviams, kertantiems i ta kelia patenkancias juostas pagal taisykles salygas (Nuoroda: KET 158).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_007_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'cl_ket_2024_12_01_158',TRUE,NOW()),
  ('qr_sc_007_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-007-turning-across-users'),'cl_ket_2024_12_01_27',TRUE,NOW());

-- SC-008
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_008','SC-008','sc-008-intersection-blocking','single','Intersection blocking','MEDIUM','Priekyje sankryzoje susidariusi spustis.','Ka turite daryti pries ivaziuodami i sankirta?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_008_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking'),'A','Neivaziuoti i sankirta, kol uz jos neatsilaisvins vieta',TRUE,NULL,'Teisinga, nes draudziama ivaziuoti i sankirta jei tektu joje sustoti ir trukdyti eismui (Nuoroda: KET 160).',NOW(),NOW()),
  ('qo_sc_008_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking'),'B','Ivaziuoti ir sustoti sankryzos viduryje, kad uzimti eile',FALSE,NULL,'Neteisinga, nes tai tiesiogiai draudziama (Nuoroda: KET 160).',NOW(),NOW()),
  ('qo_sc_008_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking'),'C','Vaziuoti tik jei spaudziama is galo',FALSE,NULL,'Neteisinga, nes priekinio eismo kliutis nekeicia draudimo blokuoti sankryza (Nuoroda: KET 160).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_008_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-008-intersection-blocking'),'cl_ket_2024_12_01_160',TRUE,NOW());

-- SC-009
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_009','SC-009','sc-009-traffic-light-arrow','single','Traffic lights','MEDIUM','Degant raudonam signalui ijungta papildomos sekcijos zalia rodykle i desine.','Kokia taisykle taikoma vaziuojant pagal papildoma rodykle?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_009_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow'),'A','Sukti rodykles kryptimi tik davus kelia is kitu krypciu leidziamu signalu judantiems eismo dalyviams',TRUE,NULL,'Teisinga, nes papildomos sekcijos rodykle su raudonu/geltonu signalu nesuteikia absoliutaus pirmumo (Nuoroda: KET 163).',NOW(),NOW()),
  ('qo_sc_009_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow'),'B','Vaziuoti be sustojimo, nes rodykle turi auksciausia pirmenybe',FALSE,NULL,'Neteisinga, nes vairuotojas privalo duoti kelia kitiems leidziamu signalu judantiems dalyviams (Nuoroda: KET 163).',NOW(),NOW()),
  ('qo_sc_009_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow'),'C','Laukti zalio pagrindinio signalo, nes rodykle negalioja',FALSE,NULL,'Neteisinga, nes papildomos sekcijos rodykle leidzia vaziuoti rodykles kryptimi su papildoma pareiga duoti kelia (Nuoroda: KET 163).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_009_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-009-traffic-light-arrow'),'cl_ket_2024_12_01_163',TRUE,NOW());

-- SC-010
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_010','SC-010','sc-010-lane-closure-merge','single','Lane closure merge','MEDIUM','Viena tos pacios krypties juosta uzblokuota ir susidare eile.','Ka privalo padaryti gretima juosta vaziuojantis vairuotojas?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_010_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge'),'A','Ileisti viena pirma eileje esancia transporto priemone persirikiuoti',TRUE,NULL,'Teisinga, nes taisykle ipareigoja gretima juosta vaziuojanti vairuotoja ileisti viena pirma eileje esancia transporto priemone (Nuoroda: KET 105).',NOW(),NOW()),
  ('qo_sc_010_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge'),'B','Neileisti nieko, nes pirmenybe visada gretimai juostai',FALSE,NULL,'Neteisinga, nes KET numato privaloma ileidimo pareiga sioje situacijoje (Nuoroda: KET 105).',NOW(),NOW()),
  ('qo_sc_010_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge'),'C','Leisti persirikiuoti tiek transporto priemoniu, kiek nori eile',FALSE,NULL,'Neteisinga, nes KET 105 kalba apie viena pirma eileje esancia transporto priemone kiekvienam vaziuojanciam vairuotojui.',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_010_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge'),'cl_ket_2024_12_01_105',TRUE,NOW()),
  ('qr_sc_010_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-010-lane-closure-merge'),'cl_ket_2024_12_01_104',TRUE,NOW());

-- SC-011
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_011','SC-011','sc-011-acceleration-lane','single','Acceleration lane','MEDIUM','Jus ivaziuojate i magistralini kelia is greitejimo juostos.','Koks teisingas veiksmas isiliejant i srauta?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_011_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane'),'A','Vaziuoti greitejimo juosta ir persirikiuoti duodant kelia pagrindiniu srautu vaziuojancioms transporto priemonems',TRUE,NULL,'Teisinga, nes is greitejimo juostos isiliejama i srauta duodant kelia pagrindiniu juostu transportui (Nuoroda: KET 112).',NOW(),NOW()),
  ('qo_sc_011_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane'),'B','Stabdyti greitejimo juostoje iki pilno laisvo kelio',FALSE,NULL,'Neteisinga, nes taisykle numato vaziuoti greitejimo juosta ir saugiai isilieti i srauta, o ne be reikalo stabdyti (Nuoroda: KET 112).',NOW(),NOW()),
  ('qo_sc_011_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane'),'C','Persirikiuoti is karto i pagrindine juosta be eismo vertinimo',FALSE,NULL,'Neteisinga, nes persirikiuojantis vairuotojas privalo duoti kelia (Nuoroda: KET 112).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_011_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-011-acceleration-lane'),'cl_ket_2024_12_01_112',TRUE,NOW());

-- SC-012
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_012','SC-012','sc-012-overtaking-right','single','Overtaking','MEDIUM','Pries jus vaziuojanti transporto priemone juda leciau, desineje yra kelkrastis ir letejimo juosta.','Ar galima apvaziuoti is desines vaziuojant kelkrasciu ar letejimo/greitejimo juosta?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_012_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right'),'A','Draudziama, isskyrus taisyklese numatytas siauras isimtis sukančioms i kaire transporto priemonems',TRUE,NULL,'Teisinga, nes taisykle draudzia tokia apvaziavimo taktika vaziuojant kelkrasciu, letejimo ar greitejimo juosta (Nuoroda: KET 125).',NOW(),NOW()),
  ('qo_sc_012_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right'),'B','Leidziama, jei priekyje vaziuojanti transporto priemone juda labai letai',FALSE,NULL,'Neteisinga, nes vien letas judejimas tokios islygos nesukuria (Nuoroda: KET 125).',NOW(),NOW()),
  ('qo_sc_012_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right'),'C','Leidziama, jei ijungtas posukio signalas',FALSE,NULL,'Neteisinga, nes signalas nepanaikina draudimo apvaziuoti is desines minetomis juostomis (Nuoroda: KET 125).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_012_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right'),'cl_ket_2024_12_01_125',TRUE,NOW()),
  ('qr_sc_012_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-012-overtaking-right'),'cl_ket_2024_12_01_119',TRUE,NOW());

-- SC-013
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_013','SC-013','sc-013-speed-limits','multi','Speed limits','HARD','Vertinami keli skirtingi greicio ribu teiginiai.','Pazymekite teisingus teiginius apie greicio ribas.',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_013_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'A','Gyvenvieteje maksimalus greitis visoms transporto priemonems yra 50 km/h',TRUE,NULL,'Teisinga, nes tai tiesiogiai nustatyta gyvenvietems (Nuoroda: KET 129).',NOW(),NOW()),
  ('qo_sc_013_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'B','Stovejimo aiksteleje maksimalus greitis yra 20 km/h',TRUE,NULL,'Teisinga, nes stovėjimo aikstelese taikomas 20 km/h limitas (Nuoroda: KET 130).',NOW(),NOW()),
  ('qo_sc_013_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'C','Lengvasis automobilis automagistraleje balandzio-spalio menesiais gali vaziuoti iki 130 km/h',TRUE,NULL,'Teisinga, nes sezoninis limitas lengviesiems automobiliams siuo laikotarpiu yra 130 km/h (Nuoroda: KET 131.1).',NOW(),NOW()),
  ('qo_sc_013_d',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'D','Pradedanciajam vairuotojui automagistraleje leidziama iki 110 km/h',FALSE,NULL,'Neteisinga, nes pradedanciajam automagistraleje leidziama iki 100 km/h (Nuoroda: KET 131.2).',NOW(),NOW()),
  ('qo_sc_013_e',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'E','Kelio zenklas gali leisti virsyti transporto priemonei 131 punkte nustatyta maksimalu limita',FALSE,NULL,'Neteisinga, nes net ir esant zenklui negalima virsyti transporto priemonei taikomo maksimalaus limito (Nuoroda: KET 132).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_013_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'cl_ket_2024_12_01_129',TRUE,NOW()),
  ('qr_sc_013_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'cl_ket_2024_12_01_130',TRUE,NOW()),
  ('qr_sc_013_3',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'cl_ket_2024_12_01_131_1',TRUE,NOW()),
  ('qr_sc_013_4',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'cl_ket_2024_12_01_131_2',TRUE,NOW()),
  ('qr_sc_013_5',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-013-speed-limits'),'cl_ket_2024_12_01_132',TRUE,NOW());

-- SC-014
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_014','SC-014','sc-014-pedestrian-crossing-stop','single','Pedestrian crossing','MEDIUM','Pries nereguliuojama pereja kita transporto priemone sustojo.','Ka privalote daryti vaziuodami ta pacia kryptimi?',NULL,'PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_014_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'A','Sustoti arba suletinti ir pradeti vaziuoti tik isitikinus, kad perejoje nera pesciojo, kuriam trukdytumete',TRUE,NULL,'Teisinga, nes pries pereja sustojus ar suletejus kitai transporto priemonei turite uztikrinti, kad nepavojingai praleidziami pestieji (Nuoroda: KET 30, 31).',NOW(),NOW()),
  ('qo_sc_014_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'B','Apvaziuoti sustojusia transporto priemone ir testi judejima per pereja',FALSE,NULL,'Neteisinga, nes tai gali sukelti pavoju perejoje esantiems pestiesiems ir pazeidzia elgesio prie perejos reikalavimus (Nuoroda: KET 31, 32).',NOW(),NOW()),
  ('qo_sc_014_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'C','Nereikia imtis veiksmu, jei nematote pesciuju',FALSE,NULL,'Neteisinga, nes vairuotojas privalo aktyviai isitikinti saugumu ir prireikus sustoti (Nuoroda: KET 30, 31).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_014_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'cl_ket_2024_12_01_30',TRUE,NOW()),
  ('qr_sc_014_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'cl_ket_2024_12_01_31',TRUE,NOW()),
  ('qr_sc_014_3',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-014-pedestrian-crossing-stop'),'cl_ket_2024_12_01_32',TRUE,NOW());

-- SC-015
INSERT INTO "public"."Question" ("id","externalId","slug","type","topic","difficulty","situationLt","promptLt","mediaUrl","status","evidenceStatus","createdAt","updatedAt")
VALUES ('q_sc_015','SC-015','sc-015-railway-crossing','image','Railway crossing','HARD','Artejate prie gelezinkelio pervazos, uz jos matoma kliutis.','Koks teisingas veiksmas sioje situacijoje?','/scenarios/railway-crossing.svg','PUBLISHED','SUFFICIENT',NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET "externalId" = EXCLUDED."externalId", "type" = EXCLUDED."type", "topic" = EXCLUDED."topic", "difficulty" = EXCLUDED."difficulty", "situationLt" = EXCLUDED."situationLt", "promptLt" = EXCLUDED."promptLt", "mediaUrl" = EXCLUDED."mediaUrl", "status" = EXCLUDED."status", "evidenceStatus" = EXCLUDED."evidenceStatus", "updatedAt" = NOW();

DELETE FROM "public"."QuestionOption" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing');
INSERT INTO "public"."QuestionOption" ("id","questionId","key","textLt","isCorrect","orderRank","explanationLt","createdAt","updatedAt")
VALUES
  ('qo_sc_015_a',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'A','Sustoti pries stop linija ar zenkla ir neivaziuoti i pervaza, jei uz jos kliutis',TRUE,NULL,'Teisinga, nes draudziama ivaziuoti i pervaza, jei uz jos kliutis, o duodant kelia privaloma sustoti nustatytose vietose (Nuoroda: KET 170, 173.4).',NOW(),NOW()),
  ('qo_sc_015_b',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'B','Greitai pervaziuoti pervaza, kad neatideti eismo',FALSE,NULL,'Neteisinga, nes pirmiausia turi buti uztikrintas saugumas ir nevaziuojama ant pervazos esant kliuciai (Nuoroda: KET 173.4).',NOW(),NOW()),
  ('qo_sc_015_c',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'C','Ivaziuoti i pervaza ir sustoti ant begiu, jei eile nejuda',FALSE,NULL,'Neteisinga, nes sustoti ant pervazos draudziama, kai uz jos kliutis (Nuoroda: KET 173.4).',NOW(),NOW());

DELETE FROM "public"."QuestionReference" WHERE "questionId" = (SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing');
INSERT INTO "public"."QuestionReference" ("id","questionId","ruleClauseId","isPrimary","createdAt")
VALUES
  ('qr_sc_015_1',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'cl_ket_2024_12_01_170',TRUE,NOW()),
  ('qr_sc_015_2',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'cl_ket_2024_12_01_173_4',TRUE,NOW()),
  ('qr_sc_015_3',(SELECT "id" FROM "public"."Question" WHERE "slug" = 'sc-015-railway-crossing'),'cl_ket_2024_12_01_169',TRUE,NOW());

COMMIT;
